=== Sambit63/InternshipAssgn/Mod-4/ExternalDTD.dtd
<!DOCTYPE students [
<!ELEMENT students (student+)>
<!ELEMENT student (sic,name,branch)>
<!ELEMENT sic (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
]>

=== Sambit63/InternshipAssgn/Mod-4/ExternalDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "ExternalDTD.dtd">
<students>
  <student>
    <sic>20becd13</sic>
    <name>Sambit</name>
    <branch>ECE</branch>
  </student>
  <student>
    <sic>20becd15</sic>
    <name>Pikun</name>
    <branch>CSE</branch>
  </student>
</students>
